### ISSUE TITLE
Drawer in AdaptiveScaffold class (no need)

### ISSUE THREAD

**Issue by igokom** [beagle-barks/adaptive_library#4]
Hello. At this moment drawer field is not used, except declaration, so it took some time for me to find out what is wrong, when i've tried use it in my project. Anyway according to that recommendation:
 https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/drawers/ ,
it could be better to remove it at all. Thanks for your time.

**Comment by benjamin-kraatz** [comment]
Hello,

you're right. Drawer field wasn't given to the Scaffold class.
I also added a small documentation to explain that some fields not work on both Material and Cupertino.
